### ISSUE TITLE
iron ingot should disappear

### ISSUE THREAD

**Issue by Gsvrgsvve** [TobyDev0207/FlatWorld#3]
When lighting a portal, iron ingot should disappear like a fire charge

**Comment by TobyDev0207** [comment]
I just released version [1.0.2](https://github.com/TobyDev0207/FlatWorld/releases/tag/1.0.2). In this version, you need to create a Heart of the Earth from grass, stones, a nether star and use it to activate the portal. Because the recipe of Heart of the Earth contains a nether star so I think it shouldn't be disappear. On the other hand, I use a library to create portals so it's a bit difficult to make the item disappear as you said. Just a little difficulty, not impossible so I think I'll make the recipes depend on the difficulty level of the game in the future. Thanks for your feedback.
